apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kube-nginx-django.name" . }}-env
  labels:
    app: nginx-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    releaseTime: "{{ date "20060102150405" .Release.Time }}"
data:
  secret_key: {{ .Values.django.secret_key | b64enc }}
  postgres-password: {{ .Values.postgresql.postgresqlPassword | b64enc }}
  postgres-user: {{ .Values.postgresql.postgresqlUsername | b64enc }}