kind: ConfigMap
apiVersion: v1
metadata:
  name: sites-enabled-configmap
data:
  ucr-app.conf: |
    server {
      listen {{ .Values.nginx.listenPort }};
      client_max_body_size 4G;

      # set the correct host(s) for your site
      server_name localhost;

      access_log /var/log/nginx/access.log combined;
      error_log  /var/log/nginx/error.log warn;

      keepalive_timeout 5;

      {{- if eq .Values.django.webDebug "True" }}
      location / {
        proxy_pass http://localhost:8000;
      }
      {{- else }}
      location /static {
        alias /var/www/html;
      }
      location / {
        try_files $uri @proxy_to_app;
      }
      location @proxy_to_app {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_pass http://localhost:8000;
        # proxy_pass http://app_server;
      }
      {{- end }}

      error_page 500 502 503 504 /500.html;
      location = /500.html {
        root /var/www/html/;
      }
    }